spring:
  application:
    name: users-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
  datasource:
    url: jdbc:postgresql://${HOST_DB:localhost:5432}/${NAME_DB:inventory_system_db}
    username: ${USERNAME_DB:postgres}
    password: ${PASSWORD_DB:postgres}
    driver-class-name: org.postgresql.Driver

server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${HOST_EUREKA:localhost:8761}/eureka/
